# Generated by Django 3.2.5 on 2021-07-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('operation', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=1)),
                ('well', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('notes', models.CharField(max_length=500)),
                ('begin_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OperationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30)),
                ('operation', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('well', models.CharField(max_length=30)),
                ('fact', models.IntegerField()),
                ('drilled', models.IntegerField()),
                ('drilled24', models.IntegerField()),
                ('last_drilled', models.IntegerField()),
                ('to_drill', models.IntegerField()),
                ('last_column', models.IntegerField()),
                ('next_column', models.IntegerField()),
                ('diameter', models.IntegerField()),
                ('days', models.IntegerField()),
                ('meeting', models.TimeField()),
                ('days_without_incident', models.IntegerField()),
                ('days_after_uncountable_case', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('plan', models.IntegerField()),
                ('fact', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('master', models.CharField(max_length=30)),
                ('supervisor', models.CharField(max_length=30)),
                ('driller', models.CharField(max_length=30)),
                ('appointment', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=30)),
                ('xcor', models.CharField(max_length=10)),
                ('ycor', models.CharField(max_length=10)),
                ('complex', models.CharField(max_length=30)),
                ('altitude', models.IntegerField()),
                ('chief', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='WellRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well', models.CharField(max_length=30)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('z', models.IntegerField()),
            ],
        ),
    ]
