# Generated by Django 3.2.5 on 2021-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0002_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateField(default='2021-07-15'),
            preserve_default=False,
        ),
    ]
