# Generated by Django 3.2.5 on 2021-07-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well', '0003_operation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('well', models.CharField(max_length=30)),
                ('count', models.IntegerField()),
                ('type_m', models.CharField(max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
