# Generated by Django 3.2.5 on 2021-07-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='group',
        ),
        migrations.AddField(
            model_name='user',
            name='current_well',
            field=models.CharField(default='sdsd', max_length=30),
            preserve_default=False,
        ),
    ]
