# Generated by Django 3.2.5 on 2021-07-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210712_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Master',
        ),
    ]
