# Generated by Django 3.2.5 on 2021-07-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Well',
        ),
    ]
