# Generated by Django 3.2.5 on 2021-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_delete_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatcher',
            name='complex',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
