# Generated by Django 3.2.5 on 2021-07-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plan', models.IntegerField()),
                ('fact', models.IntegerField(null=True)),
                ('difference', models.IntegerField()),
            ],
        ),
    ]
