# Generated by Django 3.2.5 on 2021-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_fact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='well',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
